services:
  postgres:
    image: postgres:latest
    container_name: mangapark
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - csTrade

  pgweb:
    image: sosedoff/pgweb
    container_name: pgwebMP
    restart: always
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: "postgres://postgres:postgres@mangapark:5432/postgres?sslmode=disable"
    ports:
      - "8081:8081"
    networks:
      - csTrade

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /mnt/x/docker/s3/mangapark:/data

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:latest
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - xpack.security.transport.ssl.enabled=false
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   networks:
  #     - csTrade
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data
  #   restart: always

volumes:
  pgdata:
  es_data:

networks:
  csTrade:
    driver: bridge
